Cometbft0 38 6
xian-network/xian-core pull request #40
Opened 2024-03-16 21:13 UTC by crosschainer

Everything is working now on the latest cometbft 0.38.6 including genesis deploy, completely overhauled logic...(abci+ 2.0 or whatever its called)

2024-03-16 22:26 UTC, duelingbenjos requested changes

2024-03-16 22:26 UTC, duelingbenjos commented on src/xian/xian_abci.py
> +        fingerprint_hash = hash_list(self.fingerprint_hashes)
any reason we're hashing the list twice in one block ? shouldn't it just be done once, after all the txs are processed ?

2024-03-19 22:03 UTC, Endogen approved these changes

2024-03-19 23:00 UTC, duelingbenjos approved these changes

2024-03-20 06:14 UTC, merged